#!/usr/bin/env node
// Contracts-first codegen: generates TypeScript + Python types from contracts/.
//
// Usage:
//   node scripts/codegen.mjs           # write generated files (TS + Python)
//   node scripts/codegen.mjs --ts-only # TS only (Node Docker builds without uv)
//   node scripts/codegen.mjs --check   # fail (exit 1) if generated files are out of date
import { spawnSync } from "node:child_process";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";
import openapiTS, { astToString } from "openapi-typescript";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const engineRoot = resolve(root, "apps/engine");
const check = process.argv.includes("--check");
const tsOnly = process.argv.includes("--ts-only");

const TS_HEADER = [
  "// AUTO-GENERATED by scripts/codegen.mjs from contracts/. DO NOT EDIT BY HAND.",
  "// Run `npm run codegen` to regenerate. See .cursor/rules/contracts-first.mdc",
  "",
].join("\n");

const PY_HEADER = [
  "# AUTO-GENERATED by scripts/codegen.mjs from contracts/. DO NOT EDIT BY HAND.",
  "# Run `npm run codegen` to regenerate. See .cursor/rules/contracts-first.mdc",
  "",
].join("\n");

/** @type {{ spec: string, out: string }[]} */
const openapiTargets = [
  {
    spec: resolve(root, "contracts/openapi.node.yaml"),
    out: resolve(root, "packages/shared-types/src/generated/node.ts"),
  },
  {
    spec: resolve(root, "contracts/openapi.engine.yaml"),
    out: resolve(root, "packages/shared-types/src/generated/engine.ts"),
  },
];

let drift = false;

/**
 * Compare or write generated content.
 * @param {string} out
 * @param {string} generated
 * @param {string} label
 */
async function emitGenerated(out, generated, label) {
  if (check) {
    let current = "";
    try {
      current = await readFile(out, "utf8");
    } catch {
      current = "";
    }
    if (current !== generated) {
      drift = true;
      console.error(`[codegen] OUT OF DATE: ${label}`);
    } else {
      console.log(`[codegen] up to date: ${label}`);
    }
    return;
  }
  await mkdir(dirname(out), { recursive: true });
  await writeFile(out, generated, "utf8");
  console.log(`[codegen] wrote ${out}`);
}

for (const { spec, out } of openapiTargets) {
  const ast = await openapiTS(new URL(`file://${spec}`));
  await emitGenerated(out, TS_HEADER + astToString(ast), out);
}

const jobsSchemaPath = resolve(root, "contracts/jobs.schema.json");
const jobsSchema = JSON.parse(await readFile(jobsSchemaPath, "utf8"));
const payloadTypes = await Promise.all(
  Object.entries(jobsSchema.$defs).map(([name, def]) =>
    compile({ ...def, $schema: jobsSchema.$schema }, name, {
      bannerComment: "",
      additionalProperties: false,
    }),
  ),
);
const jobsTs = [
  TS_HEADER,
  ...payloadTypes,
  "",
  "export type JobType = 'sync' | 'parse' | 'embed' | 'xrepo' | 'distill' | 'repo_cleanup';",
  "",
  "export type JobEnvelope =",
  "  | { type: 'sync'; payload: SyncPayload }",
  "  | { type: 'parse'; payload: ParsePayload }",
  "  | { type: 'embed'; payload: EmbedPayload }",
  "  | { type: 'xrepo'; payload: XrepoPayload }",
  "  | { type: 'distill'; payload: DistillPayload }",
  "  | { type: 'repo_cleanup'; payload: RepoCleanupPayload };",
  "",
].join("\n");
await emitGenerated(resolve(root, "packages/shared-types/src/generated/jobs.ts"), jobsTs, "jobs.ts");

if (!tsOnly) {
  /** @type {{ input: string, output: string, fileType: string }[]} */
  const pythonTargets = [
    {
      input: resolve(root, "contracts/jobs.schema.json"),
      output: resolve(engineRoot, "src/generated/jobs.py"),
      fileType: "jsonschema",
    },
    {
      input: resolve(root, "contracts/openapi.engine.yaml"),
      output: resolve(engineRoot, "src/generated/engine_api.py"),
      fileType: "openapi",
    },
  ];

  for (const target of pythonTargets) {
    const generated = await generatePythonModels(target.input, target.output, target.fileType);
    await emitGenerated(target.output, generated, target.output);
  }

  const pyInit = `${PY_HEADER}"""Generated contract models."""\n`;
  await emitGenerated(resolve(engineRoot, "src/generated/__init__.py"), pyInit, "generated/__init__.py");
}

if (check && drift) {
  console.error("[codegen] Generated types are out of date. Run `npm run codegen` and commit.");
  process.exit(1);
}

/**
 * Run datamodel-code-generator and prepend the standard header.
 * @param {string} input
 * @param {string} output
 * @param {string} fileType
 * @returns {Promise<string>}
 */
async function generatePythonModels(input, output, fileType) {
  await mkdir(dirname(output), { recursive: true });
  const tmpOutput = `${output}.codegen.tmp`;
  const args = [
    "run",
    "datamodel-codegen",
    "--input",
    input,
    "--input-file-type",
    fileType,
    "--output-model-type",
    "pydantic_v2.BaseModel",
    "--disable-timestamp",
    "--output",
    tmpOutput,
  ];
  const result = spawnSync("uv", args, {
    cwd: engineRoot,
    encoding: "utf8",
  });
  if (result.status !== 0) {
    const detail = [result.error?.message, result.stderr, result.stdout]
      .filter(Boolean)
      .join("\n");
    console.error(detail || "unknown error");
    throw new Error(`datamodel-codegen failed for ${input}`);
  }
  let body = await readFile(tmpOutput, "utf8");
  await unlink(tmpOutput).catch(() => {});
  if (!body.startsWith(PY_HEADER)) {
    body = `${PY_HEADER}${body}`;
  }
  if (!check) {
    await mkdir(dirname(output), { recursive: true });
    await writeFile(output, body, "utf8");
  }
  return body;
}
