#!/usr/bin/env node
// Contracts-first codegen: generates TypeScript types from contracts/ into
// packages/shared-types/src/generated/*. Python Pydantic models are generated separately
// via datamodel-code-generator (see apps/rag/README.md), since that needs the
// Python toolchain (uv). This script is the ONLY sanctioned way to update the TS types.
//
// Usage:
//   node scripts/codegen.mjs           # write generated files
//   node scripts/codegen.mjs --check   # fail (exit 1) if generated files are out of date
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const check = process.argv.includes("--check");

const HEADER = [
  "// AUTO-GENERATED by scripts/codegen.mjs from contracts/. DO NOT EDIT BY HAND.",
  "// Run `npm run codegen` to regenerate. See .cursor/rules/contracts-first.mdc",
  "",
].join("\n");

/** @type {{ spec: string, out: string }[]} */
const targets = [
  {
    spec: resolve(root, "contracts/openapi.node.yaml"),
    out: resolve(root, "packages/shared-types/src/generated/node.ts"),
  },
  {
    spec: resolve(root, "contracts/openapi.rag.yaml"),
    out: resolve(root, "packages/shared-types/src/generated/rag.ts"),
  },
];

let drift = false;

for (const { spec, out } of targets) {
  const ast = await openapiTS(new URL(`file://${spec}`));
  const generated = HEADER + astToString(ast);

  if (check) {
    let current = "";
    try {
      current = await readFile(out, "utf8");
    } catch {
      current = "";
    }
    if (current !== generated) {
      drift = true;
      console.error(`[codegen] OUT OF DATE: ${out}`);
    } else {
      console.log(`[codegen] up to date: ${out}`);
    }
  } else {
    await writeFile(out, generated, "utf8");
    console.log(`[codegen] wrote ${out}`);
  }
}

if (check && drift) {
  console.error("[codegen] Generated types are out of date. Run `npm run codegen` and commit.");
  process.exit(1);
}
